name: GitDatabase

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Run Tests
        run: python -m unittest
      - name: Install Deployment Dependencies
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo ${GITHUB_REF#refs/tags/}
          echo ${{ github.ref }}
          python -m pip install --upgrade pip
          pip install wheel twine
      - name: Build and publish
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          PACKAGE_VERSION=0.0.3 python3 setup.py sdist bdist_wheel
          twine upload dist/*